### ISSUE TITLE
Python Train.py error

### ISSUE THREAD

**Issue by AzmatKhanX** [Xilinx/logicnets#21]
bash: jsc-m: command not found
bash: jsc_s: No such file or directory
bash: jsc-s: No such file or directory
bash: jsc_m: command not found
bash: /: Is a directory

can you help me with this one as this keep on coming

**Comment by AzmatKhanX** [comment]
And docker.sh is also not working
"unable to prepare context: unable to evaluate symlinks in Dockerfile path"
please help with this as well

**Comment by nickfraser** [comment]
What exactly are you running? Can you copy/paste the specific command? Are you running this is in docker, using the provided dockerfile? Or are you installing the dependencies natively?

**Comment by nickfraser** [comment]
Closed for inactivity.
