### ISSUE TITLE
unable to mount a local directory into docker 

### ISSUE THREAD

**Issue by tsp6** [Xilinx/logicnets#25]
I want to mount a local directory into docker container where the logicnets is working. So for that I added this command :DOCKER_EXEC="-v /home/tsp/FPGA_QNN/cc-toolchain-linux:/workspace/cc-toolchain" in 45th line right after the line where the logicnets is being mounted in run-docker.sh shell script. Then when I run the container there is an error called command not found.

./docker/run-docker.sh: line 76: -v: command not found.

can you help me to resolve this issue.

Thank You

**Comment by nickfraser** [comment]
Try this:
```
DOCKER_EXEC+="-v /home/tsp/FPGA_QNN/cc-toolchain-linux:/workspace/cc-toolchain "
```

Note, the space after "cc-toolchain "

**Comment by nickfraser** [comment]
Note, this is an issue about how to write bash scripts, not related to LogicNets, so I'll only provide limited support for this.
