### ISSUE TITLE
cannot train via remote ssh connection

### ISSUE THREAD

**Issue by tsp6** [Xilinx/logicnets#29]
I have one small clarification, when I connect this docker container to vs code via remote ssh connection and try to debug this issue. When trying to run train.py file in vs code, it is not able to find or read the input dataset that is present in data folder in cybersecurity directory. But the dataset is located in the same folder and training worked in local docker container. when connected via ssh for training it is unble to read the dataset.

Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: 'data/unsw_nb15_binarized.npz'
File "/workspace/logicnets/examples/cybersecurity/dataset.py", line 21, in get_preqnt_dataset
unsw_nb15_data = np.load(data_file)
File "/workspace/logicnets/examples/cybersecurity/train.py", line 332, in
dataset['train'] = get_preqnt_dataset(dataset_cfg['dataset_file'], split="train")

If any kind of solution or discussion is appreciated and will be helpful a lot.

**Comment by tsp6** [comment]
For this you need to pass the absolute path in train.py file where the path for input dataset is defined. In detail where the  --dataset-file is parsed in argument parser and then try to train. The problem will be solved.

**Comment by nickfraser** [comment]
Thank you reporting this issue and providing your solution.
