### ISSUE TITLE
Segfaults when running the examples on some platforms

### ISSUE THREAD

**Issue by nickfraser** [Xilinx/logicnets#38]
After the recent [workaround](https://github.com/Xilinx/logicnets/commit/17389d347b45002c5bb4e95fbaeb7ed4dd1eddbd) for #30, the examples segfault on some systems. I need to track down the source of this issue - it wasn't present before the workaround (changing default installation of PyTorch from `conda` to PyPi).

Could it be related to CPU features?

Systems with the following CPUs segfault:
 - Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
 - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
 - Intel(R) Xeon(R) Silver 4116 CPU @ 2.10GHz

Systems with the following CPUs do not segfault:
 - AMD Ryzen 7 PRO 5850U
 - AMD Ryzen 9 5900HX

**Comment by DarthHyperion** [comment]
Getting segfaults on my machine as well, running the following CPU

Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

**Comment by nickfraser** [comment]
Thanks for letting me know. Can you try running #36? You will get slightly different accuracy, but I hope you won't get segfaults.

**Comment by DarthHyperion** [comment]
Yes, I ran #36 , not getting any segfaults. Thank you!

**Comment by nickfraser** [comment]
#36 appears to resolve this issue.
