### ISSUE TITLE
Re: Clarification on conversion/quantization of Floating Point Numbers to 2-bit Binary 

### ISSUE THREAD

**Issue by Sethu11** [Xilinx/logicnets#46]
Let's take JSC-S in particular, so the input bit-width as well as the output bit-width is 2. So, how do you convert or rather quantize the Floating Point Numbers in the dataset into 2-bit Binary numbers to feed them as inputs. (Image Attached for further clarification).

![image](https://github.com/Xilinx/logicnets/assets/113815598/d13b5a08-e6fb-420c-8ef4-5c0a692a0173)

How do you convert/quantize FP Numbers on the left side to Binary Numbers on the right side?

**Comment by nickfraser** [comment]
> (Image Attached for further clarification).

How have you generated these files?

> So, how do you convert or rather quantise the Floating Point Numbers in the dataset into 2-bit Binary numbers to feed them as inputs.

What exactly do you mean by "how"? There are many ways to answer this question. Do you want to know where the code is? Do you want to understand the mathematical expression?

During training, we leverage the quantisers from [brevitas](https://github.com/Xilinx/brevitas) to _learn_ a quantizer which is optimised for the problem at hand. So the parameters of the input quantization _are a property of the model themselves_, but effectively, each model performs a uniform-spaced quantization (to integers) equivalent to the formula:

```
x_quant = clip(round(x/s + b), -2, 1)
```

where `x` is the input vector and  `s` / `b` are vectors of learnt scales / biases for the dataset during training.

**Comment by Sethu11** [comment]
The left side file (in the ref. image) I saved the entire numpy array onto a .txt file from 'dataset.py' after you save the input in 'X_train_val' and output in 'y_train_val' respectively.
As to the right one, I ran 'dataset_dump.py' and got those files.
I just wanna know the mathematics behind the conversion, like how are you converting a FP Number into a 2-bit binary, that info is sufficient for me. 
If you can point me to the code for it, that's even better.

**Comment by nickfraser** [comment]
They need to be calculated from all the modules in the `pre_transform` list (BatchNorm & ScalarScaleBias). You can look at their parameters directly and from there calculate `s` & `b`. They are not pre-calculated anywhere.
