### ISSUE TITLE
Generating truth tables for 1D-Convolutional layers

### ISSUE THREAD

**Issue by gehaddahami** [Xilinx/logicnets#48]
I am trying to use the framework to process CNNs (specifically 1D-CNNs) as part of my masters thesis topic. 
I have made some scrip editing and created similar functions that are compatible with convolutional layers. 
however, for the function (generate_truth_tables()), I am facing some errors in the line but only for the first convolutional layer: 

# Retrieve the possible state space of the current neuron
connected_state_space = [input_state_space[i] for i in indices]

the error is because the in_channels for my model are 2 and cannot be changes, hence the input state space will contain two tensors only, Moreover, the indices from the fetched mask falls out of range sometimes. I will include the customized convolutional layer and the customized sparsity mask for conv layers as well for clarification. 

my mask has a fan_in size of 2 for a kernel size of 3 or 4.  hence, due to the randomization in creating the mask, the indices are out of range almost every time. 

do you have any suggestion on how to resolve that? 

The provided function is working fine for all other layers due to the sufficient no. of tensors in the input state space which is always greater than the number of fan_in 

[customized_conv_functions.py.tar.gz](https://github.com/user-attachments/files/16101047/customized_conv_functions.py.tar.gz)

**Comment by nickfraser** [comment]
Unfortunately, I cannot provide support for functionality that LogicNets doesn't currently provide.
